// Web2/src/routes/__layout.svelte
<script context="module">
    export const load = async({ session }) => {

        return {
            props: {
                session: session
            }
        }
    }
</script>

<script lang="ts">
	import Navigation from '$lib/UI/header/layouts/Navigation.svelte';
	import type { NavigationLink } from '$lib/UI/header/layouts/Navigation.svelte'
	import '../app.css';
	import type { AuthenticationSession } from '$lib/services/Infrastructure/authentication/AuthenticationSession'

	export let session: App.Session

	const getNavigationLinks = (session: AuthenticationSession | null) => {
		let navigationLinks: NavigationLink[] = [
		{
			name: 'Documentation',
			href: '/documentation'
		},
		{
			name: 'Pricing',
			href: '/pricing'
		}
		]

		if(session !== null) {
			navigationLinks.push(
				{
				name: "Account",
				href: "/account"
				}
			)
		} else {
			navigationLinks.push(
				{
				name: "Login",
				href: "/login"
				}
			)
		}

		return navigationLinks
	}
</script>

<Navigation 
	homeLink={
		{
			name: "CloudSeed",
			href: "/"
		}
	}
	allLinks={getNavigationLinks(session.session)} />

<main>
	<slot />
</main>

<footer>
	<div class="py-2 text-center">
        <a href="https://cloudseed.xyz"
          class="text-hamred">
          Built with CloudSeed
        </a>
	</div>
</footer>

<style>
</style>

// Web/components/layouts/Layout.tsx
import React, { ReactNode } from 'react'
import Head from 'next/head'

import Navigation, { NavigationLink } from './Navigation';
import { useSession } from '../../services/Authentication'

type Props = {
  children?: ReactNode
  title?: string
}

const Layout = ({ children, title = 'CloudSeed' }: Props) => {
  const sessionResponse = useSession()

  const getAllNavigationLinks = (
    userId: string | null
  ): NavigationLink[] => {
    let navigationLinks: NavigationLink[] = [
      {
        name: 'Pricing',
        href: '/pricing'
      }
    ]

    if(userId !== null) {
      navigationLinks.push(
        {
          name: "Account",
          href: "/account"
        }
      )
    } else {
      navigationLinks.push(
        {
          name: "Register",
          href: "/register"
        }
      )
    }

    return navigationLinks
  }
  
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      <header>
        <Navigation 
          homeLink={
            {
              name: "CloudSeed",
              href: '/'
            }
          }
          navigationLinks={ 
            getAllNavigationLinks(
              sessionResponse.session?.userId ?? null
            )
          } />
      </header>
      <div >
        {children}
      </div>
      <div className="py-2 text-center">
        <a href="https://cloudseed.xyz"
          className="text-hamred">
          Built with CloudSeed
        </a>
      </div>
    </div>
  )
}

export default Layout
