// Web2/src/lib/UI/status/ErrorDetails.svelte
<script context="module" lang="ts">
    export type ErrorDetailsProps = {
        title: string,
        errorItems: string[]
    }
</script>

<script lang="ts">
    import StatusDetails from './StatusDetails.svelte'

    export let props: ErrorDetailsProps
</script>

<StatusDetails
    statusDetailsProps={{
        title: props.title,
        items: props.errorItems,
        itemClasses: [],
        backgroundClasses: ['bg-red-50']
    }} />

// Web/components/status/ErrorDetails.tsx
import React from 'react'

import StatusDetails from './StatusDetails'

interface IErrorDetailsProps {
    title: string,
    errorItems: string[]
}

const ErrorDetails = (props: IErrorDetailsProps) => {
    console.error(props.errorItems);

    return (
        <StatusDetails
            title={props.title}
            items={props.errorItems}
            itemClassNames={[]}
            backgroundClassNames={['bg-red-50']} />
    )
}

export default ErrorDetails
