// Web/src/routes/terms.svelte
<script context="module">
	export const prerender = true;
</script>

<div class="max-w-7xl mx-auto py-4 px-10 sm:px-6 lg:py-20 lg:px-10">
	<h1 class="text-4xl">Terms of Service</h1>
	Updated: 2022.02.05
	<div class="py-1">
	  <h2 class="text-2xl">Overview</h2>
	  <p>
	  Put your terms here.
	  </p>
	</div>
  </div>

// Web/pages/terms.tsx
import Layout from '../components/layouts/Layout'

const TermsPage = () => {
  return (
    <Layout title="CloudSeed">
      <div className="max-w-7xl mx-auto py-4 px-10 sm:px-6 lg:py-20 lg:px-10">
        <h1 className="text-4xl">Terms of Service</h1>
        Updated: 2022.02.05
        <p>
        Most services will have some sort of Terms of Use agreement. Put that here.
        </p>
      </div>
    </Layout>
  )
}

export default TermsPage
