// Web/components/status/SuccessStatusDetails.tsx
import React from 'react'

import StatusDetails from './StatusDetails'

interface ISuccessStatusDetailsProps {
    title: string,
    successItems: string[]
}

const SuccessStatusDetails = (props: ISuccessStatusDetailsProps) => {
    return (
        <StatusDetails
            title={props.title}
            items={props.successItems}
            itemClassNames={[]}
            backgroundClassNames={['bg-green-50']} />
    )
}

export default SuccessStatusDetails

// Web2/src/lib/UI/status/SuccessStatusDetails.svelte
<script context="module" lang="ts">
    export type SuccessDetailsProps = {
        title: string,
        successItems: string[]
    }
</script>

<script lang="ts">
    import StatusDetails from './StatusDetails.svelte'

    export let props: SuccessDetailsProps
</script>

<StatusDetails
    statusDetailsProps={{
        title: props.title,
        items: props.successItems,
        itemClasses: [],
        backgroundClasses: ['bg-green-50']
    }} />
